routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/admin/web/list', 'WebsiteController@list')->name("vanilo.website.list");
Route::get('/admin/web/create', 'WebsiteController@create')->name("vanilo.website.create");
Route::post('/admin/web/store', 'WebsiteController@store')->name("vanilo.website.store");
Route::get('admin/web/{product}', 'WebsiteController@show')->name("vanilo.website.show");
Route::get('admin/web/{product}/edit', 'WebsiteController@edit')->name("vanilo.website.edit");
Route::put('admin/web/{product}', 'WebsiteController@update')->name("vanilo.website.update");
Route::delete('admin/web/{product}', 'WebsiteController@destroy')->name("vanilo.website.destroy");
Route::put('/web/property/sync/{for}/{forId}', 'WebsiteController@syncProp')->name('vanilo.web_property_value.sync');

Route::put('/web/taxonomy/{taxonomy}/sync', 'WebsiteController@syncTax')->name('vanilo.taxonomy.syncTax');


Route::get('/admin/paper/list/{taxon}', 'PaperController@list')->name("vanilo.paper.list");
Route::get('/admin/paper/create', 'PaperController@create')->name("vanilo.paper.create");
Route::post('/admin/paper/store', 'PaperController@store')->name("vanilo.paper.store");
Route::get('admin/paper/{product}', 'PaperController@show')->name("vanilo.paper.show");
Route::delete('admin/paper/{product}', 'PaperController@destroy')->name("vanilo.paper.destroy");
Route::get('admin/paper/{product}/edit', 'PaperController@edit')->name("vanilo.paper.edit");
Route::put('admin/paper/{product}', 'PaperController@update')->name("vanilo.paper.update");

Route::delete('admin/media/{medium}', 'MediaController@destroy')->name("vanilo.p_media.destroy");

Route::get('/admin/otherproducts/list', 'OtherProductController@list')->name("vanilo.other.list");
Route::get('/admin/otherproducts/create', 'OtherProductController@create')->name("vanilo.other.create");
Route::post('/admin/otherproducts/store', 'OtherProductController@store')->name("vanilo.other.store");
Route::get('admin/otherproducts/{product}', 'OtherProductController@show')->name("vanilo.other.show");
Route::get('admin/otherproducts/{product}/edit', 'OtherProductController@edit')->name("vanilo.other.edit");
Route::put('admin/otherproducts/{product}', 'OtherProductController@update')->name("vanilo.other.update");
Route::delete('admin/otherproducts/{product}', 'OtherProductController@destroy')->name("vanilo.other.destroy");

Route::get('/', 'HomeController@welcome')->name('welcome');

Route::get('/website', function () {
    return view('website');
})->name('website');
Route::get('/davetiye', function () {
    return view('davetiye');
})->name('davetiye');
Auth::routes();
Route::post('/register2', 'Auth\Register2Controller@create')->name('register2');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop', 'as' => 'product.'], function() {
    Route::get('products', 'ProductController@index')->name('index');
    Route::get('c/{taxonomyName}/{taxon}', 'ProductController@index')->name('category');
    Route::get('urunler/{product}/{color?}', 'ProductController@show')->name('show');
	Route::get('website/{product}/{color?}', 'ProductController@website_show')->name('website_show');
	Route::get('basili-urunler/{product}/{color?}', 'ProductController@davetiye_show')->name('davetiye_show');

});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
    Route::get('show', 'CartController@show')->name('show');
    Route::post('add/{id}/{color}', 'CartController@add')->name('add');
    Route::post('update/{cart_item}', 'CartController@update')->name('update');
    Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function() {
    Route::get('show', 'CheckoutController@show')->name('show');
    Route::post('submit', 'CheckoutController@submit')->name('submit');
});

Route::get('/manage/registry', 'Frontend\RegistryController@index')->name('registry');
Route::post('/add_registry_item', 'Frontend\RegistryController@add_registry_item')->name('add_registry_item');
Route::post('/remove_registry_item', 'Frontend\RegistryController@remove_registry_item')->name('remove_registry_item');
Route::post('/updata_registry_quantity', 'Frontend\RegistryController@update_registry_quantity')->name('update_registry_quantity');
Route::post('/update_registry_property', 'Frontend\RegistryController@update_registry_property')->name('update_registry_property');

Route::get('/manage', 'Frontend\ManageController@index')->name('manage_index');
Route::get('/manage/website', 'Frontend\ManageController@website_index')->name('website_manage');
Route::post('/update_website_active_modules', 'Frontend\ManageController@update_website_active_modules')->name('website_update_website_active_modules');
Route::get('/manage/website/home/', 'Frontend\ManageController@website_home_update')->name('website_home_update');
Route::get('/manage/website/registry/', 'Frontend\ManageController@website_registry_update')->name('website_registry_update');
Route::post('/manage/website/home/', 'Frontend\ManageController@website_home_update')->name('website_home_update_post');
Route::post('/ilceler', 'Frontend\ManageController@ilceler')->name('ilceler');
Route::post('/add-story', 'Frontend\ManageController@add_story')->name('website_home_add_story');
Route::post('/update-story', 'Frontend\ManageController@update_story')->name('website_home_update_story');
Route::post('/delete-story', 'Frontend\ManageController@delete_story')->name('website_home_delete_story');


Route::get('/manage/website/schedule/', 'Frontend\ManageController@website_schedule_update')->name('website_schedule_update');
Route::post('/manage/website/schedule/', 'Frontend\ManageController@website_schedule_update')->name('website_schedule_update_post');

Route::get('/website/{slug}/{module}', 'Frontend\ManageController@preview_website')->name('preview_website');
Route::post('/add_schedule_event', 'Frontend\ManageController@add_schedule_event')->name('add_schedule_event');
Route::post('/update_schedule_event', 'Frontend\ManageController@update_schedule_event')->name('update_schedule_event');
Route::post('/delete_schedule_event', 'Frontend\ManageController@delete_schedule_event')->name('delete_schedule_event');

Route::get('/manage/website/photos/', 'Frontend\ManageController@website_photos_update')->name('website_photos_update');
Route::post('/manage/website/photos/', 'Frontend\ManageController@website_photos_update')->name('website_photos_update_post');

Route::post('/setGuest', 'Frontend\ManageController@setGuest')->name('setGuest');

Route::post('/delete_website_photo', 'Frontend\ManageController@delete_website_photo')->name('delete_website_photo');


Route::get('/manage/guests', 'Frontend\GuestController@index')->name('guests');
Route::get('/deleteGuest/{id}', 'Frontend\ManageController@delete')->name('delete_guest');

Route::post('/manage/setWebsite', 'Frontend\ManageController@setWebsite')->name('setWebsite');
Route::get('/iade-ve-iptal-kosullari',function(){
	return view('iade-iptal');
});

Route::get('/kisisel-verilerin-korunmasi-aydinlatma-metni',function(){
	return view('kisisel-veri');
});
Route::get('/kullanim-sartlari',function(){
	return view('kullanim-sartlari');
});
Route::get('/veri-isleme',function(){
	return view('veri-isleme');
});
Route::get('/mesafeli-satis-sozlesmesi',function(){
	return view('mesafeli-satis');
});
Route::get('/on-bilgilendirme-formu',function(){
	return view('on-bilgilendirme');
});
Route::get('/gizlilik-politikasi',function(){
	return view('gizlilik-politikasi');
});

Route::get('/hakkimizda',function(){
	return view('hakkimizda');
});
Route::get('/sss',function(){
	return view('sss');
});
Route::get('/nedir',function(){
	return view('nedir');
});
Route::get('/nasil-calisir',function(){
	return view('nasil-calisir');
});

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductIndexRequest;
use Vanilo\Category\Contracts\Taxon;
use Vanilo\Category\Models\TaxonomyProxy;
use Vanilo\Framework\Search\ProductFinder;
use Vanilo\Product\Contracts\Product;
use Vanilo\Properties\Models\PropertyProxy;
use Vanilo\Properties\Models\PropertyValueProxy;
use App\Registry;
use Vanilo\Category\Models\TaxonProxy;
use App\File;
use App\Helpers\CategoryHelper;
class ProductController extends Controller
{
    /** @var ProductFinder */
    private $productFinder;

    public function __construct(ProductFinder $productFinder)
    {
        $this->productFinder = $productFinder;
    }

    public function index(ProductIndexRequest $request, string $taxonomyName = null, Taxon $taxon = null)
    {
		/*CategoryHelper::get();
		exit;*/
		$checklist_prop = PropertyProxy::where('name','checklist')->first();
        $taxonomies = TaxonomyProxy::get();
        $properties = PropertyProxy::get();


        if ($taxon) {
            $this->productFinder->withinTaxon($taxon);
        }else{
			$this->productFinder->withinTaxon(TaxonProxy::find(4));
		}

        foreach ($request->filters($properties) as $property => $values) {
            $this->productFinder->havingPropertyValuesByName($property, $values);
        }

		$products = $this->productFinder->paginate(10);
		foreach ($products as $akey => $product) {
			$props = $product->propertyValues->toArray();
			$ckey = array_search($checklist_prop->id, array_column($props, 'property_id'));

			$color_property = PropertyProxy::where('name','color')->first();
			$color_key = array_search($color_property->id, array_column($props, 'property_id'));


			if(!empty($props[$color_key])){
				$imgs = $product->getMedia()->toArray();
				$p_imgs = array();
				$p_cs = array();
				foreach ($product->getMedia() as $key => $value) {
					$i_color = explode('!',explode(".",explode("_",$value->file_name)[1])[0])[0];
					$p_imgs[$i_color][] = $value;
					$p_cs[] = $i_color;
				}
				$products[$akey]->colors =array_unique($p_cs);
				$products[$akey]->product_images = $p_imgs;
				$products[$akey]->active_color = $props[$color_key]["value"];
			}
			if($props[$ckey]["value"] == "true"){
				$products[$akey]->registryView = true;
			}else{
				$products[$akey]->registryView = false;
			}

			$checkRegistry = Registry::where('product',$product->id)->first();
			if($checkRegistry){
				$products[$akey]->registry = $checkRegistry;
			}else{
				$products[$akey]->registry = $checkRegistry;
			}
		}
		if($taxon){
			if($taxon->id == 2){
				return view('product.website', [
		            'products'   => $products,
		            'taxonomies' => $taxonomies,
		            'taxon'      => $taxon,
		            'properties' => $properties,
		            'filters'    => $request->filters($properties),

		        ]);
			}
			else if($taxon->id == 3){
				return view('product.davetiye', [
		            'products'   => $products,
		            'taxonomies' => $taxonomies,
		            'taxon'      => $taxon,
		            'properties' => $properties,
		            'filters'    => $request->filters($properties),

		        ]);
			}
			else{

				return view('product.index', [
					'products'   => $products,
					'taxonomies' => $taxonomies,
					'taxon'      => $taxon,
					'properties' => $properties,
					'filters'    => $request->filters($properties),

				]);
			}
		}else{
			return view('product.index', [
				'products'   => $products,
				'taxonomies' => $taxonomies,
				'taxon'      => $taxon,
				'properties' => $properties,
				'filters'    => $request->filters($properties),

			]);
		}

    }

    public function show(Product $product,$color="none")
    {
		$color_property = PropertyProxy::where('name','color')->first();
		$color_property_values = PropertyValueProxy::where('property_id',$color_property->id)->get();
		$s_ps = $product->propertyValues->toArray();
		$ckey = array_search($color_property->id, array_column($s_ps, 'property_id'));
		$imgs = $product->getMedia()->toArray();
		$p_imgs = array();
		$p_cs = array();
		foreach ($product->getMedia() as $key => $value) {
			$i_color = explode('!',explode(".",explode("_",$value->file_name)[1])[0])[0];

			$p_imgs[$i_color][] = $value;
			$p_cs[] = $i_color;

		}
		if(strrpos($color,"!")){
			$color = $s_ps[$ckey]["value"];
			$gift = true;
		}else{
			$gift = false;
			if($color == "none"){
				$color = $s_ps[$ckey]["value"];
			}
		}

		$product->color = !empty($product->propertyValues->toArray()) ? ($color):("");
        return view('product.show', [
			'product' => $product,
			'gift' => $gift,
			'color_property_values' => array_unique($p_cs),
			'selected_color' => !empty($product->propertyValues->toArray()) ? ($color):(""),
			"product_images" => $p_imgs
		]);
    }


	public function website_show(Product $product,$color="none")
    {
		$color_property = PropertyProxy::where('name','color')->first();
		$color_property_values = PropertyValueProxy::where('property_id',$color_property->id)->get();
		$s_ps = $product->propertyValues->toArray();
		$template_property = PropertyProxy::where('name','template_name')->first();
		$template_property_values = PropertyValueProxy::where('property_id',$template_property->id)->get();
		$tkey = array_search($template_property->id, array_column($s_ps, 'property_id'));

		$ckey = array_search($color_property->id, array_column($s_ps, 'property_id'));
		$imgs = $product->getMedia()->toArray();
		$p_imgs = array();
		$p_cs = array();
		foreach ($product->getMedia() as $key => $value) {
			$i_color = explode('!',explode(".",explode("_",$value->file_name)[1])[0])[0];

			$p_imgs[$i_color][] = $value;
			$p_cs[] = $i_color;

		}

		if($color == "none"){
			$color = $s_ps[$ckey]["value"];
		}
		$product->color = !empty($product->propertyValues->toArray()) ? ($color):("");
        return view('product.website-show', [
			'product' => $product,
			'color_property_values' => array_unique($p_cs),
			'selected_color' => !empty($product->propertyValues->toArray()) ? ($color):(""),
			"product_images" => $p_imgs,
			"html_file" => File::find($product->html),
			"demo" => $s_ps[$tkey]["title"]
		]);
    }

	public function davetiye_show(Product $product,$color="none")
    {
		$color_property = PropertyProxy::where('name','color')->first();
		$color_property_values = PropertyValueProxy::where('property_id',$color_property->id)->get();
		$s_ps = $product->propertyValues->toArray();
		$ckey = array_search($color_property->id, array_column($s_ps, 'property_id'));
		$imgs = $product->getMedia()->toArray();
		$p_imgs = array();
		$p_cs = array();
		foreach ($product->getMedia() as $key => $value) {
			$i_color = explode('!',explode(".",explode("_",$value->file_name)[1])[0])[0];

			$p_imgs[$i_color][] = $value;
			$p_cs[] = $i_color;

		}

		if($color == "none"){
			$color = $s_ps[$ckey]["value"];

		}
        return view('product.davetiye-show', [
			'product' => $product,
			'color_property_values' => array_unique($p_cs),
			'selected_color' => !empty($product->propertyValues->toArray()) ? ($color):(""),
			"product_images" => $p_imgs,
		]);
    }
}

resources/views/product/_breadcrumbs.blade.php
<?php
    $stack = [];
    $stack[] = [
        'url'   => route('product.category', [$taxon->taxonomy->slug, $taxon]),
        'label' => $taxon->name
    ];

    $parent = $taxon;
    while ($parent = $parent->parent) {
        $stack[] = [
            'url'   => route('product.category', [$parent->taxonomy->slug, $parent]),
            'label' => $parent->name
        ];
    }
    $stack[] = [
        'url'   => '#',
        'label' => $taxon->taxonomy->name
    ]
?>
@foreach(array_reverse($stack) as $item)
    <li class="breadcrumb-item"><a href="{{ $item['url'] }}">{{ $item['label'] }}</a></li>
@endforeach

resources/views/product/davetiye-show.blade.php
@extends('layouts.main')
@section('styles')
<link rel="stylesheet" href="{{ asset('css/davet-detay.css') }}">

@endsection

@section('scripts')
<script src="{{ asset('js/owl.carousel2.thumbs.js') }}"></script>
<script>
	$(document).ready(function(){
		$('.color-wrapper').click(function(){
			var p_url = '{!! route('product.davetiye_show',$product) !!}';
			window.location.href = p_url + "/" + $(this).data('color');
		});
	});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		var owl = $('.owl-carousel');
		owl.owlCarousel({
			loop: true,
			items: 1,
			thumbs: true,
			thumbImage: true,
			thumbContainerClass: 'owl-thumbs row',
			thumbItemClass: 'col-2'
		});

		$('.qty-prop select').change(function(){
			var qty = $(this).find('option:selected').attr('value');
			if(qty != 0){
				$('.selected-qty').html(qty);
			}
			else{
				$('.selected-qty').html("");
			}
		})
		$('.color-prop .color-wrapper').click(function(){
			$('.color-wrapper').removeClass('active');
			$(this).addClass('active');
			var color = $(this).data('title');
			$('.selected-color').html(color);
		});
		$('.paper-prop li').click(function(){
			$('.paper-prop li').removeClass('active');
			$(this).addClass('active');
			$('.selected-paper').html($(this).html());
		});
		$('.shape-prop .shape').click(function(){
			var shape = $(this).data('title');
			$('.shape-prop .shape').removeClass('active');
			$(this).addClass('active');
			$('.selected-shape').html(shape);
		})
	});
</script>
@endsection

@section('content')
<section class="davetiye-detail">
	<div class="container">
		<div class="row">
			<div class="col-md-7 image">

				<div class="owl-carousel detail-slider">
					@foreach($product_images[$selected_color] as $med)
					<div data-thumb="{{url('/storage/'.$med->id.'/'.$med->file_name)}}">
						<img src="{{url('/storage/'.$med->id.'/'.$med->file_name)}}" id="product-image" style="width:100%;"/>
					</div>

					@endforeach
				</div>
			</div>
			<div class="col-md-5 detail">
				<h1 class="title">{{$product->name}}</h1>
				<h3 class="price">{{ format_price($product->price) }}</h3>
				<div class="qty-prop">
					<h3 class="prop-title">ADET: <span class="selected-qty"></span></h3>
					<select class="">
						<option value="0">Adet Seçiniz</option>
						<option value="100">100</option>
						<option value="200">200</option>
						<option value="500">500</option>
						<option value="1000">1000</option>
						<option value="2000">2000</option>
					</select>
				</div>
				<div class="color-prop">
					<h3 class="prop-title">RENK: <span class="selected-color"></span></h3>
					<div class="colors">

						@unless(empty($product->propertyValues->toArray()))
			                @foreach($color_property_values as $property)
							<a href="javascript:void(0);">
								<div class="color-wrapper {{$selected_color == $property ? ('active'):("")}}" data-color="{{$property}}" data-title="{{$property}}">
									<div  class="color" style="background-color: {{$property}};"></div>
								</div>
							</a>
							@endforeach
						@endunless
					</div>
				</div>
				<div class="paper-prop">
					<h3 class="prop-title">KAğIT: <span class="selected-paper"></span></h3>
					<ul>
						<li>Pürüzsüz</li>
						<li>Amerikan Bristol</li>
						<li>Birinci Hamur</li>
						<li>Krem Fantezi Kağıtlar</li>
					</ul>
				</div>
				<div class="shape-prop">
					<h3 class="prop-title">ŞEKİL: <span class="selected-shape"></span></h3>
					<div class="shapes">
						<div class="shape square" data-shape="square" data-title="Kare"></div>
						<div class="shape round" data-shape="round" data-title="Yuvarlak"></div>
					</div>

				</div>
				<div class="buttons">
					<form action="{{ route('cart.add', ['id' => $product->id,'color' => $product->color]) }}" method="post" class="mb-4">
	                    {{ csrf_field() }}
						<button type="submit" class="customize-btn">Satın Al</button>
	                </form>
				</div>
				@unless(empty($product->description))
					<div class="description">
						<h4 class="s-title">Açıklama</h4>
						<p>
							{!!  nl2br($product->description) !!}
						</p>
					</div>
                @endunless
				<div class="description">
					<h4 class="s-title">Ayrıntılar</h4>
					<p>
					{!!  nl2br($product->excerpt) !!}
					</p>
				</div>
				<div class="description" style="display:none;">
					<h4 class="s-title">Tahmini Varış</h4>
					<p>
						Tüm siparişler ücretsiz gönderilir ve 5-10 iş günü içinde teslim edilir. Not: Uzun nakliye süreleri nedeniyle uluslararası olarak veya Alaska ve Hawaii'ye gönderim yapmıyoruz.
					</p>
				</div>
				<div class="description" style="display:none;">
					<h4 class="s-title">Kargo İade</h4>
					<p>
						Uzmanlarımız, davetiyeyle ilgili tüm sorularınızı cevaplayacaktır. Ayrıca, çalışmanızı yazdırılmadan önce kanıtlamanıza ve son dakikada bir hata tespit etmeniz durumunda iki saatlik bir iptal penceresine sahip olmanıza izin vereceğiz.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="related">
	<div class="container">
		<h1 class="title">Diğer Davetiye Tasarımlarına Gözatın</h1>
		<div class="row">
			<div class="col-md-3 item">
				<div class="item-inner">
					<a href="#"><img src="{{ asset('img/related-davetiye.jpg') }}" /></a>
					<a href="#"><h2 class="item-title">Davet - Octavia portre</h2></a>
					<span class="price">34,00 ₺</span>
					<div class="colors">
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 item">
				<div class="item-inner">
					<a href="#"><img src="{{ asset('img/related-davetiye.jpg') }}" /></a>
					<a href="#"><h2 class="item-title">Davet - Octavia portre</h2></a>
					<span class="price">34,00 ₺</span>
					<div class="colors">
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 item">
				<div class="item-inner">
					<a href="#"><img src="{{ asset('img/related-davetiye.jpg') }}" /></a>
					<a href="#"><h2 class="item-title">Davet - Octavia portre</h2></a>
					<span class="price">34,00 ₺</span>
					<div class="colors">
						<a href="#">
							<div class="color-wrapper" data-color="red">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper" data-color="blue">
								<div class="color" style="background-color: blue;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper" data-color="yellow">
								<div class="color" style="background-color: yellow;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper" data-color="green">
								<div class="color" style="background-color: green;"></div>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-md-3 item">
				<div class="item-inner">
					<a href="#"><img src="{{ asset('img/related-davetiye.jpg') }}" /></a>
					<a href="#"><h2 class="item-title">Davet - Octavia portre</h2></a>
					<span class="price">34,00 ₺</span>
					<div class="colors">
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
						<a href="#">
							<div class="color-wrapper">
								<div class="color" style="background-color: red;"></div>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/product/website-show.blade.php
@extends('layouts.main')
@section('styles')
<link rel="stylesheet" href="{{ asset('css/website-detay.css') }}">

@endsection

@section('scripts')
<script>
	$(document).ready(function(){
		$('.color-wrapper').click(function(){
			var p_url = '{!! route('product.website_show',$product) !!}';
			window.location.href = p_url + "/" + $(this).data('color');
		});
	});
</script>
@endsection

@section('content')
<section class="website-detail">
	<div class="container">
		<div class="row">
			<div class="col-md-7 image">

				@foreach($product_images[$selected_color] as $med)
					<img src="{{url('/storage/'.$med->id.'/'.$med->file_name)}}" id="product-image" style="width:100%;"/>
				@endforeach
			</div>
			<div class="col-md-5 detail">
				<h1 class="title">{{$product->name}}</h1>
				<h3 class="price">{{ format_price($product->price) }}</h3>
				<h3 class="color-title">RENK:</h3>
				<div class="colors">
					@unless(empty($product->propertyValues->toArray()))
		                @foreach($color_property_values as $property)
						<a href="javascript:void(0);">
							<div class="color-wrapper {{$selected_color == $property ? ('active'):("")}}" data-color="{{$property}}">
								<div  class="color" style="background-color: {{$property}};"></div>
							</div>
						</a>
						@endforeach
					@endunless
				</div>
				<div class="buttons">
					<form action="{{ route('cart.add', ['id' => $product->id,'color' => $product->color]) }}" method="post" class="mb-4">
	                    {{ csrf_field() }}
						<button type="submit" class="customize-btn">Satın Al</button>
	                </form>

					<a href="/websites/{{$demo}}/demo.html" target="_blank" class="preview-btn">Önizleme</a>
				</div>
				@unless(empty($product->description))
					<div class="description">
						<h4 class="s-title">Açıklama</h4>
						<p>
							{!!  nl2br($product->description) !!}
						</p>
					</div>
                @endunless

				<div class="description">
					<h4 class="s-title">Ayrıntılar</h4>
					<p>
					{!!  nl2br($product->excerpt) !!}
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection