routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/admin/web/list', 'WebsiteController@list')->name("vanilo.website.list");
Route::get('/admin/web/create', 'WebsiteController@create')->name("vanilo.website.create");
Route::post('/admin/web/store', 'WebsiteController@store')->name("vanilo.website.store");
Route::get('admin/web/{product}', 'WebsiteController@show')->name("vanilo.website.show");
Route::get('admin/web/{product}/edit', 'WebsiteController@edit')->name("vanilo.website.edit");
Route::put('admin/web/{product}', 'WebsiteController@update')->name("vanilo.website.update");
Route::delete('admin/web/{product}', 'WebsiteController@destroy')->name("vanilo.website.destroy");
Route::put('/web/property/sync/{for}/{forId}', 'WebsiteController@syncProp')->name('vanilo.web_property_value.sync');

Route::put('/web/taxonomy/{taxonomy}/sync', 'WebsiteController@syncTax')->name('vanilo.taxonomy.syncTax');


Route::get('/admin/paper/list/{taxon}', 'PaperController@list')->name("vanilo.paper.list");
Route::get('/admin/paper/create', 'PaperController@create')->name("vanilo.paper.create");
Route::post('/admin/paper/store', 'PaperController@store')->name("vanilo.paper.store");
Route::get('admin/paper/{product}', 'PaperController@show')->name("vanilo.paper.show");
Route::delete('admin/paper/{product}', 'PaperController@destroy')->name("vanilo.paper.destroy");
Route::get('admin/paper/{product}/edit', 'PaperController@edit')->name("vanilo.paper.edit");
Route::put('admin/paper/{product}', 'PaperController@update')->name("vanilo.paper.update");

Route::delete('admin/media/{medium}', 'MediaController@destroy')->name("vanilo.p_media.destroy");

Route::get('/admin/otherproducts/list', 'OtherProductController@list')->name("vanilo.other.list");
Route::get('/admin/otherproducts/create', 'OtherProductController@create')->name("vanilo.other.create");
Route::post('/admin/otherproducts/store', 'OtherProductController@store')->name("vanilo.other.store");
Route::get('admin/otherproducts/{product}', 'OtherProductController@show')->name("vanilo.other.show");
Route::get('admin/otherproducts/{product}/edit', 'OtherProductController@edit')->name("vanilo.other.edit");
Route::put('admin/otherproducts/{product}', 'OtherProductController@update')->name("vanilo.other.update");
Route::delete('admin/otherproducts/{product}', 'OtherProductController@destroy')->name("vanilo.other.destroy");

Route::get('/', 'HomeController@welcome')->name('welcome');

Route::get('/website', function () {
    return view('website');
})->name('website');
Route::get('/davetiye', function () {
    return view('davetiye');
})->name('davetiye');
Auth::routes();
Route::post('/register2', 'Auth\Register2Controller@create')->name('register2');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop', 'as' => 'product.'], function() {
    Route::get('products', 'ProductController@index')->name('index');
    Route::get('c/{taxonomyName}/{taxon}', 'ProductController@index')->name('category');
    Route::get('urunler/{product}/{color?}', 'ProductController@show')->name('show');
	Route::get('website/{product}/{color?}', 'ProductController@website_show')->name('website_show');
	Route::get('basili-urunler/{product}/{color?}', 'ProductController@davetiye_show')->name('davetiye_show');

});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
    Route::get('show', 'CartController@show')->name('show');
    Route::post('add/{id}/{color}', 'CartController@add')->name('add');
    Route::post('update/{cart_item}', 'CartController@update')->name('update');
    Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function() {
    Route::get('show', 'CheckoutController@show')->name('show');
    Route::post('submit', 'CheckoutController@submit')->name('submit');
});

Route::get('/manage/registry', 'Frontend\RegistryController@index')->name('registry');
Route::post('/add_registry_item', 'Frontend\RegistryController@add_registry_item')->name('add_registry_item');
Route::post('/remove_registry_item', 'Frontend\RegistryController@remove_registry_item')->name('remove_registry_item');
Route::post('/updata_registry_quantity', 'Frontend\RegistryController@update_registry_quantity')->name('update_registry_quantity');
Route::post('/update_registry_property', 'Frontend\RegistryController@update_registry_property')->name('update_registry_property');

Route::get('/manage', 'Frontend\ManageController@index')->name('manage_index');
Route::get('/manage/website', 'Frontend\ManageController@website_index')->name('website_manage');
Route::post('/update_website_active_modules', 'Frontend\ManageController@update_website_active_modules')->name('website_update_website_active_modules');
Route::get('/manage/website/home/', 'Frontend\ManageController@website_home_update')->name('website_home_update');
Route::get('/manage/website/registry/', 'Frontend\ManageController@website_registry_update')->name('website_registry_update');
Route::post('/manage/website/home/', 'Frontend\ManageController@website_home_update')->name('website_home_update_post');
Route::post('/ilceler', 'Frontend\ManageController@ilceler')->name('ilceler');
Route::post('/add-story', 'Frontend\ManageController@add_story')->name('website_home_add_story');
Route::post('/update-story', 'Frontend\ManageController@update_story')->name('website_home_update_story');
Route::post('/delete-story', 'Frontend\ManageController@delete_story')->name('website_home_delete_story');


Route::get('/manage/website/schedule/', 'Frontend\ManageController@website_schedule_update')->name('website_schedule_update');
Route::post('/manage/website/schedule/', 'Frontend\ManageController@website_schedule_update')->name('website_schedule_update_post');

Route::get('/website/{slug}/{module}', 'Frontend\ManageController@preview_website')->name('preview_website');
Route::post('/add_schedule_event', 'Frontend\ManageController@add_schedule_event')->name('add_schedule_event');
Route::post('/update_schedule_event', 'Frontend\ManageController@update_schedule_event')->name('update_schedule_event');
Route::post('/delete_schedule_event', 'Frontend\ManageController@delete_schedule_event')->name('delete_schedule_event');

Route::get('/manage/website/photos/', 'Frontend\ManageController@website_photos_update')->name('website_photos_update');
Route::post('/manage/website/photos/', 'Frontend\ManageController@website_photos_update')->name('website_photos_update_post');

Route::post('/setGuest', 'Frontend\ManageController@setGuest')->name('setGuest');

Route::post('/delete_website_photo', 'Frontend\ManageController@delete_website_photo')->name('delete_website_photo');


Route::get('/manage/guests', 'Frontend\GuestController@index')->name('guests');
Route::get('/deleteGuest/{id}', 'Frontend\ManageController@delete')->name('delete_guest');

Route::post('/manage/setWebsite', 'Frontend\ManageController@setWebsite')->name('setWebsite');
Route::get('/iade-ve-iptal-kosullari',function(){
	return view('iade-iptal');
});

Route::get('/kisisel-verilerin-korunmasi-aydinlatma-metni',function(){
	return view('kisisel-veri');
});
Route::get('/kullanim-sartlari',function(){
	return view('kullanim-sartlari');
});
Route::get('/veri-isleme',function(){
	return view('veri-isleme');
});
Route::get('/mesafeli-satis-sozlesmesi',function(){
	return view('mesafeli-satis');
});
Route::get('/on-bilgilendirme-formu',function(){
	return view('on-bilgilendirme');
});
Route::get('/gizlilik-politikasi',function(){
	return view('gizlilik-politikasi');
});

Route::get('/hakkimizda',function(){
	return view('hakkimizda');
});
Route::get('/sss',function(){
	return view('sss');
});
Route::get('/nedir',function(){
	return view('nedir');
});
Route::get('/nasil-calisir',function(){
	return view('nasil-calisir');
});

app/Registry.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Registry extends Model
{
    protected $table = 'registry_items';
    protected $fillable = [
        'user',
        'product',
		'quantity',
		'property'
    ];
}

app/Http/Controllers/Frontend/RegistryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Requests\ProductIndexRequest;
use Vanilo\Category\Contracts\Taxon;
use Vanilo\Category\Models\TaxonomyProxy;
use App\ProductFinder2;
use Vanilo\Product\Contracts\Product;
use Vanilo\Properties\Models\PropertyProxy;
use Vanilo\Properties\Models\PropertyValueProxy;
use Illuminate\Http\Request;
use App\Registry;
use Vanilo\Product\Models\ProductProxy;

class RegistryController extends \App\Http\Controllers\Controller
{
    /** @var ProductFinder2 */
    private $productFinder;
    public function __construct(ProductFinder2 $productFinder)
    {
        $this->productFinder = $productFinder;
    }
    public function index(ProductIndexRequest $request)
    {
		$properties = PropertyProxy::get();
		$registry_items = Registry::where('user',$request->user()->id)->get();
		$product_ids = array();
		foreach ($registry_items as $ri_key => $ri) {
			$product_ids[] = $ri->product;
		}
		$this->productFinder->getIds($product_ids);
		foreach ($request->filters($properties) as $property => $values) {
            $this->productFinder->havingPropertyValuesByName($property, $values);
        }
		$products = $this->productFinder->getResults();
		foreach ($products as $akey => $product) {
			$props = $product->propertyValues->toArray();
			$color_property = PropertyProxy::where('name','color')->first();
			$color_key = array_search($color_property->id, array_column($props, 'property_id'));
			if(!empty($props[$color_key])){
				$imgs = $product->getMedia()->toArray();
				$p_imgs = array();
				$p_cs = array();
				foreach ($product->getMedia() as $key => $value) {
					$i_color = explode('!',explode(".",explode("_",$value->file_name)[1])[0])[0];
					$p_imgs[$i_color][] = $value;
					$p_cs[] = $i_color;
				}
				$products[$akey]->colors =array_unique($p_cs);
				$products[$akey]->product_images = $p_imgs;
				$products[$akey]->active_color = $props[$color_key]["value"];
			}
			$checkRegistry = Registry::where('product',$product->id)->first();
			if($checkRegistry){
				$products[$akey]->registry = $checkRegistry;
			}else{
				$products[$akey]->registry = $checkRegistry;
			}
		}
		return view('registry.index', [
			"properties" => $properties,
			"products" => $products,
			'filters'    => $request->filters($properties),
			"taxon" => null
        ]);
    }
	public function add_registry_item(Request $request){
		$registry = Registry::create([
			"user" => $request->user()->id,
			"product" => $request->product,
			"quantity" => $request->quantity,
			"property" => $request->property
		]);
		return ["Success" =>true,"registry_id" => $registry->id];
	}
	public function remove_registry_item(Request $request){
		$registry = Registry::find($request->id);
		$registry->delete();
		return ["Success" => true];
	}

	public function update_registry_quantity(Request $request){
		$registry = Registry::find($request->id);
		$registry->quantity = $request->quantity;
		$registry->save();
		return ["Success" => true];
	}
	public function update_registry_property(Request $request){
		$registry = Registry::find($request->id);
		$registry->property = $request->property;
		$registry->save();
		return ["Success" => true];
	}
}

resources/views/registry/index/_category.blade.php
<article class="card shadow-sm">
    <div class="card-body">
        <h5><a href="{{ route('product.category', [$taxon->taxonomy->name, $taxon]) }}">{{ $taxon->name }}</a></h5>
    </div>
</article>

resources/views/registry/index/_category_level.blade.php
@foreach($taxons as $taxon)
<div class="pl-{{$taxon->level}}">
    @if($taxon->children->count())
        <div class="dropdown-divider"></div>
        {{--<h6 class="dropdown-header">{{ $taxon->name }}</h6>--}}
        <a href="{{ route('product.category', [$taxon->taxonomy->slug, $taxon]) }}" class="dropdown-item dropdown-header">
            {{ $taxon->name }}
        </a>
        @include('product.index._category_level', ['taxons' => $taxon->children])
        <div class="dropdown-divider"></div>
    @else
        <a class="dropdown-item" href="{{ route('product.category', [$taxon->taxonomy->slug, $taxon]) }}">{{ $taxon->name }}</a>
    @endif
</div>
@endforeach

resources/views/registry/index/_filters.blade.php
<form class="card card-default mb-3" action="{{
    $taxon ?
    route('product.category', [$taxon->taxonomy->slug, $taxon])
    :
    route('product.index')
}}">
    <div class="card-header">Filters
        <button class="btn btn-sm btn-primary float-right pt-0 pb-0">Apply</button>
    </div>
    <ul class="list-group list-group-flush">
        @foreach($properties as $property)
            @include('product.index._property', ['property' => $property, 'filters' => $filters[$property->slug] ?? []])
        @endforeach
    </ul>
</form>

resources/views/registry/index/_product.blade.php
<div class="col-md-4 theme">
	<div class="img-wrapper">
		@foreach($product->product_images as $img_key => $imgs)
			<div class="product_image p_img_{{$product->id}} p_img_{{$product->id}}_{{$img_key}} {{$img_key == $product->active_color ? ('active'):('')}}">
				<a href="{{ route('product.show', $product) }}" class="product_link_{{$product->id}}" data-baselink="{{ route('product.show', $product) }}">
					<img class="card-img-top" src="{{url('/storage/'.$imgs[0]->id.'/'.$imgs[0]->file_name)}}" alt="{{ $product->name }}" />
				</a>
			</div>
		@endforeach
	</div>
	<a href="{{ route('product.show', $product) }}" data-baselink="{{ route('product.show', $product) }}" class="product_link_{{$product->id}}"><h2 class="title">{{ $product->name }}</h2></a>
	<span class="price">{{ format_price($product->price) }}</span>

	<div class="colors" style="display:flex;">
		@if($product->colors)
			@php
				$i = 0;
			@endphp
			@foreach($product->colors as $color)
				<div data-prop="color,{{$color}}" data-registry="{{$product->registry->id}}" class="color-wrapper registry-color product-color color {{$color}} product-color{{$product->id}} {{'color,'.$color == $product->registry->property ? ('active'):('')}}" data-product="{{$product->id}}" data-color="{{$color}}">
					<div class="color-b" style="background-color:{{$color}};"></div>
				</div>
				@php
					$i++;
				@endphp
			@endforeach
		@endif
	</div>
	<div class="non-registry-view non-registry-view{{$product->id}}" style="display:block;">
		<div style="display:flex;justify-content:space-between;margin-bottom:10px;margin-top:20px;">
			<input type="number" class="registry-quantity quantity{{$product->id}}" value="{{$product->registry->quantity}}" style="width:48%;"/>
			<a href="javascript:void(0);" data-registry="{{$product->registry->id}}" data-product="{{$product->id}}" class="update-quantity float-right pt-0 pb-0 registry-btn"  style="width:48%;">Güncelle</a>
		</div>

		<a data-product="{{$product->id}}" href="javascript:void(0);" data-registry="{{$product->registry->id}}" class="remove-registry remove-registry2 remove-registry{{$product->id}} registry-btn " style="width:100%;">Hediye Listesinden Kaldır</a>
	</div>

</div>

resources/views/registry/index/_product2.blade.php
<div class="col-md-6 theme">
	<div class="img-wrapper">
		@foreach($product->product_images as $img_key => $imgs)
			<div class="product_image p_img_{{$product->id}} p_img_{{$product->id}}_{{$img_key}} {{$img_key == $product->active_color ? ('active'):('')}}">
				<a href="{{ route('product.show', $product) }}" class="product_link_{{$product->id}}" data-baselink="{{ route('product.show', $product) }}">
					<img class="card-img-top" src="{{url('/storage/'.$imgs[0]->id.'/'.$imgs[0]->file_name)}}" alt="{{ $product->name }}" />
				</a>
			</div>
		@endforeach
	</div>
	<a href="{{ route('product.show', $product) }}" data-baselink="{{ route('product.show', $product) }}" class="product_link_{{$product->id}}"><h2 class="title">{{ $product->name }}</h2></a>

</div>

resources/views/registry/index/_property.blade.php
@if($property->id != 1 && $property->id != 5)
<div class="filter prop-filter">
	<h3>{{ $property->name }}</h3>
	<div>
		<ul>
			@foreach($property->values() as $propertyValue)
				<li>
			    <div class="custom-control custom-checkbox">
			        <input type="checkbox" class="custom-control-input" name="{{ $property->slug }}[]"
			               value="{{ $propertyValue->value }}" id="filter-{{$propertyValue->id}}"
			               @if(in_array($propertyValue->value, $filters)) checked="checked" @endif
			        >
			        <label class="custom-control-label" for="filter-{{$propertyValue->id}}">{{ $propertyValue->title }}</label>
			    </div>
				</li>
			@endforeach
		</ul>
	</div>
</div>

@endif