routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/admin/web/list', 'WebsiteController@list')->name("vanilo.website.list");
Route::get('/admin/web/create', 'WebsiteController@create')->name("vanilo.website.create");
Route::post('/admin/web/store', 'WebsiteController@store')->name("vanilo.website.store");
Route::get('admin/web/{product}', 'WebsiteController@show')->name("vanilo.website.show");
Route::get('admin/web/{product}/edit', 'WebsiteController@edit')->name("vanilo.website.edit");
Route::put('admin/web/{product}', 'WebsiteController@update')->name("vanilo.website.update");
Route::delete('admin/web/{product}', 'WebsiteController@destroy')->name("vanilo.website.destroy");
Route::put('/web/property/sync/{for}/{forId}', 'WebsiteController@syncProp')->name('vanilo.web_property_value.sync');

Route::put('/web/taxonomy/{taxonomy}/sync', 'WebsiteController@syncTax')->name('vanilo.taxonomy.syncTax');


Route::get('/admin/paper/list/{taxon}', 'PaperController@list')->name("vanilo.paper.list");
Route::get('/admin/paper/create', 'PaperController@create')->name("vanilo.paper.create");
Route::post('/admin/paper/store', 'PaperController@store')->name("vanilo.paper.store");
Route::get('admin/paper/{product}', 'PaperController@show')->name("vanilo.paper.show");
Route::delete('admin/paper/{product}', 'PaperController@destroy')->name("vanilo.paper.destroy");
Route::get('admin/paper/{product}/edit', 'PaperController@edit')->name("vanilo.paper.edit");
Route::put('admin/paper/{product}', 'PaperController@update')->name("vanilo.paper.update");

Route::delete('admin/media/{medium}', 'MediaController@destroy')->name("vanilo.p_media.destroy");

Route::get('/admin/otherproducts/list', 'OtherProductController@list')->name("vanilo.other.list");
Route::get('/admin/otherproducts/create', 'OtherProductController@create')->name("vanilo.other.create");
Route::post('/admin/otherproducts/store', 'OtherProductController@store')->name("vanilo.other.store");
Route::get('admin/otherproducts/{product}', 'OtherProductController@show')->name("vanilo.other.show");
Route::get('admin/otherproducts/{product}/edit', 'OtherProductController@edit')->name("vanilo.other.edit");
Route::put('admin/otherproducts/{product}', 'OtherProductController@update')->name("vanilo.other.update");
Route::delete('admin/otherproducts/{product}', 'OtherProductController@destroy')->name("vanilo.other.destroy");

Route::get('/', 'HomeController@welcome')->name('welcome');

Route::get('/website', function () {
    return view('website');
})->name('website');
Route::get('/davetiye', function () {
    return view('davetiye');
})->name('davetiye');
Auth::routes();
Route::post('/register2', 'Auth\Register2Controller@create')->name('register2');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop', 'as' => 'product.'], function() {
    Route::get('products', 'ProductController@index')->name('index');
    Route::get('c/{taxonomyName}/{taxon}', 'ProductController@index')->name('category');
    Route::get('urunler/{product}/{color?}', 'ProductController@show')->name('show');
	Route::get('website/{product}/{color?}', 'ProductController@website_show')->name('website_show');
	Route::get('basili-urunler/{product}/{color?}', 'ProductController@davetiye_show')->name('davetiye_show');

});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
    Route::get('show', 'CartController@show')->name('show');
    Route::post('add/{id}/{color}', 'CartController@add')->name('add');
    Route::post('update/{cart_item}', 'CartController@update')->name('update');
    Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function() {
    Route::get('show', 'CheckoutController@show')->name('show');
    Route::post('submit', 'CheckoutController@submit')->name('submit');
});

Route::get('/manage/registry', 'Frontend\RegistryController@index')->name('registry');
Route::post('/add_registry_item', 'Frontend\RegistryController@add_registry_item')->name('add_registry_item');
Route::post('/remove_registry_item', 'Frontend\RegistryController@remove_registry_item')->name('remove_registry_item');
Route::post('/updata_registry_quantity', 'Frontend\RegistryController@update_registry_quantity')->name('update_registry_quantity');
Route::post('/update_registry_property', 'Frontend\RegistryController@update_registry_property')->name('update_registry_property');

Route::get('/manage', 'Frontend\ManageController@index')->name('manage_index');
Route::get('/manage/website', 'Frontend\ManageController@website_index')->name('website_manage');
Route::post('/update_website_active_modules', 'Frontend\ManageController@update_website_active_modules')->name('website_update_website_active_modules');
Route::get('/manage/website/home/', 'Frontend\ManageController@website_home_update')->name('website_home_update');
Route::get('/manage/website/registry/', 'Frontend\ManageController@website_registry_update')->name('website_registry_update');
Route::post('/manage/website/home/', 'Frontend\ManageController@website_home_update')->name('website_home_update_post');
Route::post('/ilceler', 'Frontend\ManageController@ilceler')->name('ilceler');
Route::post('/add-story', 'Frontend\ManageController@add_story')->name('website_home_add_story');
Route::post('/update-story', 'Frontend\ManageController@update_story')->name('website_home_update_story');
Route::post('/delete-story', 'Frontend\ManageController@delete_story')->name('website_home_delete_story');


Route::get('/manage/website/schedule/', 'Frontend\ManageController@website_schedule_update')->name('website_schedule_update');
Route::post('/manage/website/schedule/', 'Frontend\ManageController@website_schedule_update')->name('website_schedule_update_post');

Route::get('/website/{slug}/{module}', 'Frontend\ManageController@preview_website')->name('preview_website');
Route::post('/add_schedule_event', 'Frontend\ManageController@add_schedule_event')->name('add_schedule_event');
Route::post('/update_schedule_event', 'Frontend\ManageController@update_schedule_event')->name('update_schedule_event');
Route::post('/delete_schedule_event', 'Frontend\ManageController@delete_schedule_event')->name('delete_schedule_event');

Route::get('/manage/website/photos/', 'Frontend\ManageController@website_photos_update')->name('website_photos_update');
Route::post('/manage/website/photos/', 'Frontend\ManageController@website_photos_update')->name('website_photos_update_post');

Route::post('/setGuest', 'Frontend\ManageController@setGuest')->name('setGuest');

Route::post('/delete_website_photo', 'Frontend\ManageController@delete_website_photo')->name('delete_website_photo');


Route::get('/manage/guests', 'Frontend\GuestController@index')->name('guests');
Route::get('/deleteGuest/{id}', 'Frontend\ManageController@delete')->name('delete_guest');

Route::post('/manage/setWebsite', 'Frontend\ManageController@setWebsite')->name('setWebsite');
Route::get('/iade-ve-iptal-kosullari',function(){
	return view('iade-iptal');
});

Route::get('/kisisel-verilerin-korunmasi-aydinlatma-metni',function(){
	return view('kisisel-veri');
});
Route::get('/kullanim-sartlari',function(){
	return view('kullanim-sartlari');
});
Route::get('/veri-isleme',function(){
	return view('veri-isleme');
});
Route::get('/mesafeli-satis-sozlesmesi',function(){
	return view('mesafeli-satis');
});
Route::get('/on-bilgilendirme-formu',function(){
	return view('on-bilgilendirme');
});
Route::get('/gizlilik-politikasi',function(){
	return view('gizlilik-politikasi');
});

Route::get('/hakkimizda',function(){
	return view('hakkimizda');
});
Route::get('/sss',function(){
	return view('sss');
});
Route::get('/nedir',function(){
	return view('nedir');
});
Route::get('/nasil-calisir',function(){
	return view('nasil-calisir');
});

app/Http/Controllers/CheckoutController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CheckoutRequest;
use Konekt\Address\Models\CountryProxy;
use Vanilo\Cart\Contracts\CartManager;
use Vanilo\Checkout\Contracts\Checkout;
use Vanilo\Order\Contracts\OrderFactory;
use Vanilo\Product\Models\ProductProxy;
use Vanilo\Order\Models\OrderProxy;
use App\Website;
use App\ModuleData;
use Illuminate\Support\Str;
use App\User;
class CheckoutController extends Controller
{
    /** @var Checkout */
    private $checkout;

    /** @var Cart */
    private $cart;

    public function __construct(Checkout $checkout, CartManager $cart)
    {
        $this->checkout = $checkout;
        $this->cart     = $cart;
    }

    public function show()
    {
        $checkout = false;

        if ($this->cart->isNotEmpty()) {
            $checkout = $this->checkout;
            if ($old = old()) {
                $checkout->update($old);
            }

            $checkout->setCart($this->cart);
        }

        return view('checkout.show', [
            'checkout'  => $checkout,
            'countries' => CountryProxy::all()
        ]);
    }

    public function submit(CheckoutRequest $request, OrderFactory $orderFactory)
    {

        $this->checkout->update($request->all());
        $this->checkout->setCustomAttribute('notes', $request->get('notes'));
		$this->checkout->setCustomAttribute('isWebsite', "");
        $this->checkout->setCart($this->cart);
        $order = $orderFactory->createFromCheckout($this->checkout);
		foreach ($order->items()->get() as $key => $value) {
			$p = ProductProxy::find($value->product_id);
			if($p->html != 0){

				$o = OrderProxy::find($order->id);
				$o->isWebsite = $p->id;
				$o->save();
				$user = User::find($request->user()->id);
				$user->website = $p->id;
				$user->save();
				$website = Website::create([
					"user" => $order->user_id,
					"product" => $p->id,
					"slug" => Str::slug($request->user()->name . " ". $request->user()->id,"-"),
					"status" => "nonvisible",
					"active_modules" => [
						"home" => true,
						"schedule" => false,
						"registry" => false,
						"photos" => false,
						"sss" => false
					]
				]);

				ModuleData::create([
					"website" => $website->id,
					"module" => "home",
					"data" => [
						"il" => 0,
						"date" => 0,
						"ilce" => "",
						"title" => "",
						"address" => "",
						"hashtag" => "",
						"page_title" => "",
						"page_message" => "",
						"main_image" => 0,
						"bottom_image" => 0
					]
				]);
				ModuleData::create([
					"website" => $website->id,
					"module" => "schedule",
					"data" => [
						"title" => "",
						"description" => "",
					]
				]);
			}
		}
        $this->cart->destroy();

        return view('checkout.thankyou', ['order' => $order]);
    }

}

resources/views/checkout/_billing_address.blade.php
<div class="form-group row">
	<div class="col-md-12">
		<label>{{ __('Ülke') }}</label>

	        {{ Form::select('billpayer[address][country_id]', $countries->pluck('name', 'id'),
	                setting('appshell.default.country'), [
	                'class' => 'form-control' . ($errors->has('billpayer.address.country_id') ? ' is-invalid' : '')
	            ])
	        }}

	        @if ($errors->has('billpayer.address.country_id'))
	            <div class="invalid-feedback">{{ $errors->first('billpayer.address.country_id') }}</div>
	        @endif
	</div>


</div>

<div class="form-group row">
	<div class="col-md-12">
	    <label class="">{{ __('Adres') }}</label>
		{{ Form::text('billpayer[address][address]', null, [
				'class' => 'form-control' . ($errors->has('billpayer.address.address') ? ' is-invalid' : '')
			])
		}}
		@if ($errors->has('billpayer.address.address'))
			<div class="invalid-feedback">{{ $errors->first('billpayer.address.address') }}</div>
		@endif
	</div>
</div>

<div class="form-group row">
	<div class="col-md-12">
    	<label>{{ __('Posta Kodu') }}</label>

        {{ Form::text('billpayer[address][postalcode]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.postalcode') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.postalcode'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.postalcode') }}</div>
        @endif
	</div>
</div>

<div class="form-group row">
	<div class="col-md-12">
		<label>{{ __('Şehir') }}</label>
		{{ Form::text('billpayer[address][city]', null, [
				'class' => 'form-control' . ($errors->has('billpayer.address.city') ? ' is-invalid' : '')
			])
		}}
		@if ($errors->has('billpayer.address.city'))
			<div class="invalid-feedback">{{ $errors->first('billpayer.address.city') }}</div>
		@endif
	</div>
</div>

resources/views/checkout/_billpayer.blade.php
<div class="checkoutbox">

	<div class="form-group row">
		<div class="col-md-12">
			<h3>FATURA ADRESİ</h3>
			{{ Form::text('billpayer[firstname]', null, [
					'class' => 'form-control' . ($errors->has('billpayer.firstname') ? ' is-invalid' : ''),
					'placeholder' => __('Ad')
				])
			}}

			@if ($errors->has('billpayer.firstname'))
				<div class="invalid-feedback">{{ $errors->first('billpayer.firstname') }}</div>
			@endif
		</div>

	</div>
	<div class="form-group row">
		<div class="col-md-12">
			{{ Form::text('billpayer[lastname]', null, [
					'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
					'placeholder' => __('Soyad')
				])
			}}

			@if ($errors->has('billpayer.lastname'))
				<div class="invalid-feedback">{{ $errors->first('billpayer.lastname') }}</div>
			@endif
		</div>

	</div>



	<div class="form-group row">
		<div class="col-md-12">
			<div class="form-check">
		        <input class="form-check-input" id="chk_is_organization" type="checkbox"
		               name="billpayer[is_organization]" value="1" v-model="isOrganization">
		        <label class="form-check-label" for="chk_is_organization">{{ __('Fatura İstiyorum') }}</label>
		    </div>
		</div>

	</div>

	<div id="billpayer-organization" v-show="isOrganization">
	    <div class="form-group row">
			<div class="col-md-12">
				{{ Form::text('billpayer[company_name]', null, [
			   		 'class' => 'form-control form-control-lg' . ($errors->has('billpayer.company_name') ? ' is-invalid' : ''),
			   		 'placeholder' => __('Şirket Adı')
			   	  ])
			    }}
			    @if ($errors->has('billpayer.company_name'))
			   	 <div class="invalid-feedback">{{ $errors->first('billpayer.company_name') }}</div>
			    @endif
			</div>
	    </div>

	    <div class="form-group row">
			<div class="col-md-12">
				{{ Form::text('billpayer[tax_nr]', null, [
		                'class' => 'form-control' . ($errors->has('billpayer.tax_nr') ? ' is-invalid' : ''),
		                'placeholder' => __('Vergi No.')
		            ])
		        }}
		        @if ($errors->has('billpayer.tax_nr'))
		            <div class="invalid-feedback">{{ $errors->first('billpayer.tax_nr') }}</div>
		        @endif
			</div>

	    </div>
	</div>
	@include('checkout._billing_address', ['address' => $billpayer->getBillingAddress()])
</div>

resources/views/checkout/_shipping_address.blade.php
<div id="shipping-address" v-show="!shipToBillingAddress">
    <h3>Shipping Address</h3>
    <hr>

    <div class="form-group row">

        <label class="col-form-label col-md-2">{{ __('İsim') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[name]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.name') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.name'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.name') }}</div>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label class="col-form-label col-md-2">{{ __('Ülke') }}</label>
        <div class="col-md-10">
            {{ Form::select('shippingAddress[country_id]', $countries->pluck('name', 'id'),
                    setting('appshell.default.country'), [
                    'class' => 'form-control' . ($errors->has('shippingAddress.country_id') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.country_id'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.country_id') }}</div>
            @endif
        </div>
    </div>

    <div class="form-group row">

        <label class="col-form-label col-md-2">{{ __('Adres') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[address]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.address') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.address'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.address') }}</div>
            @endif
        </div>
    </div>

    <div class="form-group row">

        <label class="col-form-label col-md-2">{{ __('Posta Kodu') }}</label>
        <div class="col-md-4">
            {{ Form::text('shippingAddress[postalcode]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.postalcode') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.postalcode'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.postalcode') }}</div>
            @endif
        </div>

        <label class="col-form-label col-md-2">{{ __('Şehir') }}</label>
        <div class="col-md-4">
            {{ Form::text('shippingAddress[city]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.city') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.city'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.city') }}</div>
            @endif
        </div>

    </div>
</div>

resources/views/checkout/show.blade.php
@extends('layouts.main')
@section('styles')
<link href="{{ asset('css/style.css') }}" rel="stylesheet">
<style>
	.checkout_ul{
		margin:0;
		padding:0;
		list-style-type: none;
	}
	.checkout_ul li a{
		font-family:  'Source Sans Pro';
		font-weight: 400;
		font-size: 14px;
		color: #333333;
	}
	.checkout-btn{
		border:1px solid #29ABE2;
		background: #29ABE2;
		border-radius: 19px;
		font-family:  'Source Sans Pro';
		font-weight: 700;
		font-size: 14px;
		color: #FFFFFF;
		letter-spacing: 0;
		width:100%;
		height: 40px;
		display: flex;
		justify-content: center;
		align-items: center;
		margin-top: 24px;
	}
	.ch-form{
		margin-top:50px;
		margin-bottom: 50px;
	}
	.checkoutbox{
		background: #FFFFFF;
		box-shadow: 0 2px 28px 0 rgba(0,0,0,0.05);
		border-radius: 9px;
		padding-left:50px;
		padding-right: 50px;
		padding-bottom: 30px;
		padding-top: 30px;
		margin-bottom:20px;
	}
	label{
		font-family:  'Source Sans Pro';
		font-weight: 400;
		font-size: 14px;
		color: #333333;
	}
	.checkoutbox h3{
		font-family:  'Source Sans Pro';
		font-weight: 700;
		font-size: 14px;
		color: #333333;
	}
	.kargo{
		font-family:  'Source Sans Pro';
		font-weight: 400;
		font-size: 14px;
		color: #333333;
	}
	.kargo input{
		margin-right: 5px;
	}
	 input[type="text"]{
		border: 1px solid #E6E6E6;
		border-radius: 20.5px!important;
		height: 40px;
		font-family:  'Source Sans Pro';
		font-weight: 400;
		font-size: 12px;
		color: #777677;
	}
	 input[type="text"]:focus{
		border-color: #29ABE2;
	}
	textarea{
	   border: 1px solid #E6E6E6;
	   border-radius: 20.5px!important;
	   height: 250px;
	   font-family:  'Source Sans Pro';
	   font-weight: 400;
	   font-size: 12px;
	   color: #777677;
   }
	textarea:focus{
	   border-color: #29ABE2;
   }
	select{
		border: 1px solid #E6E6E6;
		border-radius: 20.5px!important;
		height: 40px;
		font-family:  'Source Sans Pro';
		font-weight: 400;
		font-size: 12px;
		color: #777677;
		appearance: none;
		-webkit-appearance: none;
		-moz-appearance: none;
	}
	#shipping-address{
		margin-top: 20px;
	}
</style>
@endsection
@section('content')
    <style>
        .product-image {
            max-width: 100%;
            display: block;
            margin-bottom: 2em;
        }
    </style>
    <div class="container ch-form">
        <div class="row">
            <div class="col-md-8">
				@unless ($checkout)
					<div class="alert alert-warning">
						<p>Hey, nothing to check out here!</p>
					</div>
				@endunless

				@if ($checkout)
					<form style="margin-bottom: 30px;" id="checkout" action="{{ route('checkout.submit') }}" method="post">
						{{ csrf_field() }}
						<div class="checkoutbox">
							<div class="form-group row">
								<h3>TESLİMAT BİLGİLERİ</h3>
							</div>
							<div class="form-group">
								<div class="col-md-12 row d-flex justify-content-between" style="flex-wrap:wrap;">
									<div class="kargo">
										<input type="radio" name="options" value="red" autocomplete="off" checked> Aras Kargo(Ücretsiz)
									</div>
									<div class="kargo">
										<input type="radio" name="options" value="red" autocomplete="off"> Yurtiçi Kargo(7.25 TL)
									</div>
									<div class="kargo">
										<input type="radio" name="options" value="red" autocomplete="off" checked> UPS(10 TL)
									</div>
									<div class="kargo">
										<input type="radio" name="options" value="red" autocomplete="off" checked> Hızlı Teslimat(50 TL)
									</div>
								</div>
							</div>
						</div>
						@include('checkout._billpayer', ['billpayer' => $checkout->getBillPayer()])
						<div class="checkoutbox">
							<div class="form-group row">
								<h3>ÖDEME BİLGİLERİ</h3>
							</div>
							<div class="form-group row">
								<div class="col-md-6">
									{{ Form::text('billpayer[lastname]', null, [
											'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
											'placeholder' => __('Kart Sahibi')
										])
									}}
								</div>
								<div class="col-md-6">
									{{ Form::text('billpayer[lastname]', null, [
											'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
											'placeholder' => __('Kart Numarası')
										])
									}}
								</div>
							</div>
							<div class="form-group row">
								<div class="col-md-4">
									{{ Form::text('billpayer[lastname]', null, [
											'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
											'placeholder' => __('AA')
										])
									}}
								</div>
								<div class="col-md-4">
									{{ Form::text('billpayer[lastname]', null, [
											'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
											'placeholder' => __('YYYY')
										])
									}}
								</div>
								<div class="col-md-4">
									{{ Form::text('billpayer[lastname]', null, [
											'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
											'placeholder' => __('CVV')
										])
									}}
								</div>
							</div>
						</div>
						<div class="checkoutbox">

							<div class="form-group row">
								<h3>SİPARİŞ NOTLARI</h3>
								{{ Form::textarea('notes', null, [
										'class' => 'form-control' . ($errors->has('notes') ? ' is-invalid' : ''),
										'rows' => 3
									])
								}}
								@if ($errors->has('notes'))
									<div class="invalid-feedback">{{ $errors->first('notes') }}</div>
								@endif
							</div>
						</div>


						<div>
							<ul class="checkout_ul">
							<li>
								<input type="checkbox" name="Mesafeli_Satış_Sözleşmesi"> <span><a href="/mesafeli-satis-sozlesmesi"><u>Mesafeli Satış Sözleşmesini</u> kabul ediyorum.</a></span>
							</li>
							<li>
								<input type="checkbox" name="Ön_Bilgilendirme_Formu"> <span><a href="/on-bilgilendirme-formu"><u>Ön bilgilendirme formunu</u> kabul ediyorum.</a></span>
							</li>
							<li>
								<input type="checkbox" name="Aydınlatma_Formu"> <span><a href="/kisisel-verilerin-korunmasi-aydinlatma-metni"><u>Aydınlatma formunu</u> kabul ediyorum.</a></span>
							</li>
						</ul>
							<button class="checkout-btn">SİPARİŞ VER</button>
						</div>


					</form>
				@endif
            </div>
            <div class="col-md-4">
				<div class="checkoutbox">
					@include('cart._summary')
				</div>

            </div>
        </div>
    </div>
@endsection
@section('scripts')
<script>
	document.addEventListener("DOMContentLoaded", function(event) {
		new Vue({
			el: '#checkout',
			data: {
				isOrganization: {{ old('billpayer.is_organization') ?: 0 }},
				shipToBillingAddress: {{ old('ship_to_billing_address') ?? 1 }}
			}
		});
	});
</script>
<script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/checkout/thankyou.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}">All Products</a></li>
    <li class="breadcrumb-item"><a href="{{ route('cart.show') }}">Cart</a></li>
    <li class="breadcrumb-item">Checkout</li>
    <li class="breadcrumb-item">Order Complete</li>

@stop

@section('content')
    <div class="container">
        <h1>Wonderful {{ $order->getBillpayer()->firstname }}!</h1>
        <hr>

        <div class="alert alert-success">Your order has been registered with number
            <strong>{{ $order->getNumber() }}</strong>.
        </div>

        <h3>Next Steps</h3>

        <ol>
            <li>Your order will be prepared in the next 24 hours.</li>
            <li>Your package will be handed over to the courier.</li>
            <li>You'll receive an E-mail with the Shipment Information.</li>
        </ol>

        <div>
            <a href="{{ route('product.index') }}" class="btn btn-info">All right!</a>
        </div>

    </div>
@endsection